-- CREATE TABLE fire_area_canada_usa_unions (
--     year INTEGER NOT NULL,
--     geometry geometry(Geometry,3978),
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
--     PRIMARY KEY ("year", "id")
-- );


-- CREATE INDEX idx_fire_area_canada_usa_unions_geometry
--     ON 
--         fire_area_canada_usa_unions
--     USING 
--         GIST ("geometry");


INSERT INTO 
    fire_area_canada_usa_unions (year, geometry) 
SELECT 
    {{YEAR}} 
        AS year,
    ST_Union(simple_geometry) 
        AS geometry
    FROM 
        fire_area_canada_usa{{YEAR}};